services:
  postgres:
    image: postgres:16.8-alpine3.20
    container_name: task4
    environment:
      POSTGRES_USER: cuerno
      POSTGRES_PASSWORD: cuerno
      POSTGRES_DB: task4_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: